### ISSUE TITLE
Video file seek bar

### ISSUE THREAD

**Issue by ashwin31** [RacingTadpole/django-private-media#4]
Video file served with this app is not getting proper seek bar functionality.
Is it working for you?

**Comment by matheo** [comment]
@ashwin31 Did you managed to stream videos with this or another Django app? Thanks in advance for any info about it

**Comment by jagadeeshv16** [comment]
Hi @matheo, we were unable to seek videos with django-private-media. but it helped us in understanding the way private files can be served so we made modification accordingly to NGINX directly.

**Comment by matheo** [comment]
@jagadeeshv16 but still with django checking the permissions to the video first? do you mind sharing some code? please
